# Generated by Django 3.0.5 on 2020-05-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategorieAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': "Categorie d'agents",
                'verbose_name_plural': "Categories d'agents",
            },
        ),
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Dimension DATE',
                'verbose_name_plural': 'Dimensions DATE',
            },
        ),
        migrations.CreateModel(
            name='Periodicite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
                ('dim_date_column_name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeActivite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': "Type d'activites",
                'verbose_name_plural': "Types d'activites",
            },
        ),
        migrations.CreateModel(
            name='PeriodeReporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodes_reporting', to='CentreApp.Activite')),
                ('periodicite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodes_reporting', to='CentreApp.Periodicite')),
            ],
            options={
                'verbose_name': 'Periode de reporting',
                'verbose_name_plural': 'Periodes de reporting',
            },
        ),
        migrations.CreateModel(
            name='FactPrestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('quantite', models.IntegerField()),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='CentreApp.Activite')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='CentreApp.DimDate')),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(blank=True, max_length=50, null=True)),
                ('categorie_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='CentreApp.CategorieAgent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activite',
            name='categorie_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='CentreApp.CategorieAgent'),
        ),
        migrations.AddField(
            model_name='activite',
            name='type_activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites', to='CentreApp.TypeActivite'),
        ),
    ]
