# Generated by Django 3.0.5 on 2020-05-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentreApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fact_Prestation',
            new_name='FactPrestation',
        ),
    ]
